stages:
  - topog
topog:
  stage: topog
  tags:
    - gfdl
  timeout: 1 hours 0 minutes
  script:
  - export PYTHONPATH="/net2/nnz/opt/miniconda/lib/python3.8/site-packages"; export PATH="/net2/nnz/opt/miniconda/bin:$PATH";
  - ". activate platforms"
  - which python
  - pwd
  - (cd testing; ln -s /net2/nnz/datasets .datasets ; make)
variables:
  GIT_STRATEGY: clone