stages:
  - topog
topog:
  stage: topog
  tags:
    - gfdl
  timeout: 1 hours 0 minutes
  script:
  - module load miniforge
  - conda activate /net2/nnz/opt/miniconda/envs/platforms
  - which python
  - pwd
  - (cd testing; ln -s /net2/nnz/datasets .datasets ; make)
variables:
  GIT_STRATEGY: clone
